steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-west1-docker.pkg.dev/tienda-microservices-429001/image-registry/products-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-west1-docker.pkg.dev/tienda-microservices-429001/image-registry/products-ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/184206400683/secrets/producst_database_url/versions/1
    env: 'DATABASE_URL'
  - versionName: projects/184206400683/secrets/products_database_direct_url/versions/1
    env: 'DIRECT_URL'